[package]
name = "agent-rs"
version = "0.0.1"
edition = "2021"


[dependencies]
axum = "*"
tokio = { version = "1.43.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"